[theme]
primaryColor = "#DD1D21"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#FFF8E1"
textColor = "#333333"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
maxUploadSize = 200

[browser]
gatherUsageStats = false
